version: '3.7'


services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - ${API_PORT}:8000
    env_file:
      - .env

  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
  